### PR TITLE
Use pip service in importers pipeline.

### LINKED ISSUE #160: Support PIP via HTTP to the PIP Service
Loading all of WOF into memory for every importer is not ideal, and very time consuming. While it might be slightly higher latency to do PIP calls over HTTP, the overall throughput of talking to the PIP service should be similar, which is all that matters for imports. The savings in memory usage would allow us to scale up importing as well, and might help imports be faster overall.

Connects https://github.com/pelias/openstreetmap/issues/345

### PR DESCRIPTION
**Pull request by tadjik1**
Hi there.

It should resolve #160.
For getting data from remote pip service update config with these values:

```
{
  "imports": {
    "adminLookup": { "enabled": true },
    "services": {
      "pip": {
        "url": "http://mypipservice.com"
      }
    }
  }
}
```

With this configuration module will perform a request for each document to get admin hierarchy.

At the same time these changes do not break anything existing, so it's fully backward compatibility.

### CODE REVIEW

**Comment by dianashk** [comment]
Hey @tadjik1, thank you so much for this excellent pull request! We've been talking about doing for a long time and we really appreciate you taking the time to do this work.
A few things we really 😍  about your solution:
- it's fully backward-compatible, so if we keep the config as it is, nothing changes!
- it's got tests, which we really ❤️  
- you've even updated the README 🚀 

We're testing the code locally to make sure it does what we'd expect and we'll leave our feedback here as soon as we're done.
Again many thanks for your thoughtful work! You rock! 🎸 ⭐️

**Comment by tadjik1** [comment]
@dianashk thanks a lot, it's very exciting to contribute in pelias!

please note that I've changed schema for config a bit. `services`  now moved to `imports` key in order to be identical as for api (there `services` key locates under `api` top-level key).

**Comment by orangejulius** [comment]
Oh and I expect to merge this in a couple hours: we are running a build using the HTTP PIP service in our dev environment, and just want to test things out. We should know for sure by tomorrow Eastern US time :)

**Comment by tadjik1** [comment]
@orangejulius regarding perfomance:
in-memory solution in my machine 2037 imports/sec
remote pip-service (which runs on local machine as well) 1200 imports/sec

but I've tested on small number of docs (~20k). it's very interesting how it will behave on large numbers.

**Comment by orangejulius** [comment]
Hey @tadjik1,
We discovered that setting [HTTP keepAlives](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_new_agent_options) to on really helps with performance. Before, on AWS we were only getting 150 imports/sec, and after the fully expected 1000-2000. It's a small change, so we'll just add it ourselves in a follow up PR.

**Pull request merged**
