### PR TITLE
made missing data file non-fatal

### PR DESCRIPTION
**Pull request by trescube**
References pelias/whosonfirst#209

### CODE REVIEW

**Comment by orangejulius** [comment]
Can we revert this? We decided a while back that [all admin lookup file load failures should be fatal](https://github.com/pelias/pelias/issues/477#issuecomment-265002768) to protect against admin lookup failing silently. It's better to have to figure out what's wrong with the data after a loud build failure.

**Comment by trescube** [comment]
We could, but there are 2 types of failures:

- git-lfs not used
- bundles are bad

In the former case, sure, since that's the users' problem.  In the latter case, I'd prefer to keep loading since it seems unfair to punish users who did everything right and there's a WOF bundles failure.  

We can certainly discuss further though.

**Comment by orangejulius** [comment]
Yeah, that's a good point. I do know that we've had our builds delayed for several weeks due to bundle issues, which is super annoying. On the other hand, with this change in, every build could potentially have any major city (except one we have acceptance tests for) lose admin data, and we wouldn't know. Let us discuss!!

**Comment by orangejulius** [comment]
Maybe the solution is a `--ignore-missing` flag (the solution to every problem seems to be a flag). That way, builds can by default ensure integrity, but if there is a legit bundle issue, there is a way for people to work around it.

**Pull request merged**
