### PR TITLE
Disable postal cities in Australia

### PR DESCRIPTION
**Pull request by orangejulius**
Australia has a one-to-many mapping of postcodes to locality names.

For example, [postcode 2671](https://auspost.com.au/postcode/2617) corresponds to 9 different suburbs, each represented as a locality in WOF.

The postal cities code in this project really only supports one-to-one or many-to-one mappings of postcodes to localities.

### CODE REVIEW

**Comment by missinglink** [comment]
@orangejulius I'm not sure if we should delete the data files?
we have a lot of other countries in the repo which are not currently being used, so we should either delete them all or none of them?

historically they were all included because we didn't know which ones we'd end up using and it was nice to have them available for examination and discussion.

**Comment by missinglink** [comment]
Particularly `AUS.override.tsv` which is small and wouldn't be recoverable via 🤖

**Comment by orangejulius** [comment]
Ah, is there a simpler way I missed to disable the postal cities lookup in Australia besides deleting the data files?

Even if not, I'm not too concerned: git never forgets, so if we need to make changes later we'll be ok.

**Comment by missinglink** [comment]
Yea this is the bit which controls which files are loaded:
https://github.com/pelias/wof-admin-lookup/blob/master/src/postalCityMap.js#L36-L45

**Comment by missinglink** [comment]
'tis true that git never forgets but it's a bit of a pain to link to and the links don't update as the code/data does:
https://github.com/pelias/pelias/issues/777#issuecomment-583409201

Either way we go, it's inconsistent right now and so we can either delete all the data we're not using or include it, the former has the benefit of a reduced git repo (or not since I already committed them?) and the latter has the benefit that the community can see them, link them and discuss them.

**Pull request merged**
