### PR TITLE
 Supports for WOF SQLite database

### PR DESCRIPTION
**Pull request by Joxit**
Don't forget to update package.json when https://github.com/pelias/whosonfirst/pull/417 is merged and released.

### CODE REVIEW

**Comment by missinglink** [comment]
@joxit, we'll need to update this PR to also support `importPlaces` :(
I had a look at doing it and it's a bit of a mess because the config object isn't passed down to where we need it...

any ideas how it might be best to achieve that?

**Comment by Joxit** [comment]
Hum... Yes it will be tricky... Maybe we should add `pelias-config` in workers and retrieve both `importPlaces` and `sqlite`?

The other solution would be `stringify() ` or `join(', ')`  `importPlaces` without spaces and add it to args... Again..

**Comment by missinglink** [comment]
Hmm.. yea It sounds like require-ing `pelias-config` is probably the way to go, I don't like dependency injection when it gets super messy like this.

I will have a look at this tomorrow Berlin-time, feel free to push a commit if you have time before then.

**Comment by Joxit** [comment]
I updated the branch.
So I added pelias-config for workers (and remove dataType from worker calls)

I noticed something with the tests. Due to `child_process` it's a bit difficult to inject to workers the right pelias-config. So I cheated, I created a fake configuration file and put it in the PELIAS_CONFIG env.

Time to sleep :sleeping:

**Comment by Joxit** [comment]
Yes, sure !

**Comment by Joxit** [comment]
Updated + rebase to master

**Comment by missinglink** [comment]
This is another case of the Travis-CI integration not working, I'm not sure why this keeps happening.
I can see from the Travis website that the job was kicked-off and passed https://travis-ci.org/pelias/pip-service/builds/507878811

**Comment by missinglink** [comment]
I tested this out fairly thoroughly in https://github.com/pelias/pip-service/issues/105 so it's good-to-merge.

**Comment by Joxit** [comment]
Yeah! Happy to see this ! :rocket: :full_moon_with_face:

**Pull request merged**
